rules:
- id: frappe-codeinjection-eval
  patterns:
  - pattern-not: eval("...")
  - pattern: eval(...)
  message: |
    Detected the use of eval(). eval() can be dangerous if used to evaluate
    dynamic content. Avoid it or use safe_eval().
  languages: [python]
  severity: ERROR

- id: require-permission-decorator-on-conversion-methods
  patterns:
  - pattern-inside: |
      class $CLASS(...):
        ...
  - pattern: |
       def $CONVERSION_METHOD(...):
         ...
  - pattern-not: |
      @requires_permission(...)
      def $CONVERSION_METHOD(...):
        ...
  - pattern-not: |
      @frappe.requires_permission(...)
      def $CONVERSION_METHOD(...):
        ...
  - metavariable-regex:
      metavariable: '$CONVERSION_METHOD'
      regex: '^_(from|into)_(.*)$'
  message: |
    '$CONVERSION_METHOD' in '$CLASS' crosses doctype boundaries.
    Explicitly declare its extended security context with @frappe.requires_permission(<doctype>, <perm>).
  languages: [python]
  severity: ERROR
  paths:
      include:
        - "*/**/doctype/*"

